-- INSERT INTO board_tb(title, content, username, created_at) VALUES ('제목1', '내용1', 'Kenneth', now());
-- INSERT INTO board_tb(title, content, username, created_at) VALUES ('제목2', '내용2', 'Minsu', now());
-- INSERT INTO board_tb(title, content, username, created_at) VALUES ('제목3', '내용3', 'Kim', now());
-- INSERT INTO board_tb(title, content, username, created_at) VALUES ('제목4', '내용4', 'Danny', now());
-- INSERT INTO board_tb(title, content, username, created_at) VALUES ('제목5', '내용5', 'Youngju', now());
-- INSERT INTO board_tb(title, content, username, created_at) VALUES ('제목6', '내용6', 'Lee', now());